### ISSUE TITLE
Wait for all Actors to complete before exiting Julia

### ISSUE THREAD

**Issue by jwscook** [JuliaActors/Actors.jl#20]
I've put the [Table Tennis example](https://juliahub.com/docs/Actors/LA8B4/0.2.2/basics/#table-tennis) into a file to run i.e. `julia file.jl`, but I find that it exits before anything is printed. How would I go about inserting a synchronisation / barrier / wait functionality so that all the tasks complete? I've seen the `await` function, but can't think how to incorporate it.

I've got a fairly ugly work around using an `Atomic{Bool}` and a `sleep(0)`, but I'm sure there's a better way?

```julia
using Actors, Random, Base.Threads

import Actors: spawn

struct Player{S,T}
  name::S
  skill::T
end

struct Ball{T,S,L}
  returndifficulty::T
  name::S
  from::L
end

struct Serve{L}
  to::L
end

struct Win{S,L}
  winner::S
  loser::L
end

inplay = Threads.Atomic{Bool}(true)

function (p::Player)(commentator, b::Ball)
  if p.skill ≥ b.returndifficulty
    send(b.from, Ball(rand(), p.name, self()))
    send(commentator, p.name * " returns to " * b.name * " on thread $(threadid())")
  else
    send(self(), Win(b.name, p.name))
  end
end

function (p::Player)(commentator, s::Serve)
  send(s.to, Ball(rand(), p.name, self()))
  send(commentator, p.name * " serves ")
end

function (p::Player)(commentator, w::Win)
  send(commentator, w.winner * " beats " * w.loser)
  inplay[] = false
end

# seeds Random.THREAD_RNGs (Vector of MersenneTwisters)
@threads for i in 1:nthreads()
  Random.seed!(threadid())
end

function run()
  commentator = spawn(println, thrd=2)
  ping = spawn(Player("Ping", 0.95), commentator, thrd=3)
  pong = spawn(Player("Pong", 0.85), commentator, thrd=4)

  send(ping, Serve(pong));
end

run()

while inplay[]; sleep(0); end
```

where I have to add `while inplay[]; sleep(0); end` to keep the script alive long enough to see output.

With `while inplay[]; sleep(0); end` I get:

```bash
$julia file.jl
Ping serves 
Pong returns to Ping on thread 4
Ping returns to Pong on thread 3
Ping beats Pong
```

and without (no output):

```bash
$julia file.jl
```

**Comment by pbayer** [comment]
Hi,

thank you very much for trying this stuff out. The canonical solution is very simple but far from obvious for most programmers.

1. In concurrent programs we can resort to our intuition about real world problems: We have two players and a commentator **and** the public (Julia) which leaves the playground before the game finishes. Obviously the public needs a signal to know about the end of the game.
2. You can think about it also as "everything being an actor". In your configuration Julia is the 4th actor taking down the runtime before it can print out.

In both cases the solution is to send a message to yourself/the runtime. For example 
- define a message `struct Stop end`,
- have a channel `me = newLink()`,
- write a commentator behavior taking `me` as an acquaintance parameter and forwarding `Stop()` to `me` and doing `println(msg)` otherwise,
- let the player send a `Stop()` message to the `commentator` after he has lost the ball,
- at the end of the `run` function do a `receive(me)`.

What do you think?

**Comment by jwscook** [comment]
Wonderful! Thanks very much. Below is my implementation of your suggestion.

```julia
using Actors, Random, Base.Threads

import Actors: spawn

struct Player{S,T}
  name::S
  skill::T
end

struct Ball{T,S,L}
  returndifficulty::T
  name::S
  from::L
end

struct Serve{L}
  to::L
end

struct Win{S,L}
  winner::S
  loser::L
end

struct Stop end

function (p::Player)(commentator, b::Ball)
  if p.skill ≥ b.returndifficulty
    send(b.from, Ball(rand(), p.name, self()))
    send(commentator, p.name * " returns to " * b.name * " on thread $(threadid())")
  else
    send(self(), Win(b.name, p.name))
    send(commentator, Stop())
  end
end

function (p::Player)(commentator, s::Serve)
  send(s.to, Ball(rand(), p.name, self()))
  send(commentator, p.name * " serves ")
end

function (p::Player)(commentator, w::Win)
  send(commentator, w.winner * " beats " * w.loser)
end

# seeds Random.THREAD_RNGs (Vector of MersenneTwisters)
@threads for i in 1:nthreads()
  Random.seed!(threadid())
end

function run()
  spectators = Actors.newLink()
  behaviour(phrase::String) = println(phrase)
  behaviour(stop::Stop) = send(spectators, stop)
  commentator = spawn(behaviour, thrd=2)
  ping = spawn(Player("Ping", 0.95), commentator, thrd=3)
  pong = spawn(Player("Pong", 0.85), commentator, thrd=4)

  send(ping, Serve(pong));
  receive(spectators)
end

run()
```

**Comment by pbayer** [comment]
great
